"""empty message

Revision ID: e1fa2348c559
Revises: cc9c3cf567ac
Create Date: 2023-09-12 15:37:34.303154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fa2348c559'
down_revision = 'cc9c3cf567ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('user_dob_key', type_='unique')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_dob_key', ['dob'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
